language: python
python:
  - "2.7"
  - "3.5"

cache:
  directories:
    - lektor/admin/node_modules

install:
  - pip install --editable .

script: make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
